//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HocPhi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string TenAdmin { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> role { get; set; }
        public string MaGiaoVien { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
    }
}
